server:
  port: 17600

spring:
    datasource:
        url:  "jdbc:postgresql://127.0.0.1:5432/Personal?user=postgres&password=secret"


dubbo:
    application:
         name: BudgetRPC
    registry:
         address: nacos://127.0.0.1:8848
